;;; product-closed-loop.scm — Part 3: CLI Commands

(define (show-status)
  (display "=== Product Closed-Loop Status ===\n")
  (display "Deploy base: ") (display DEPLOY-BASE) (newline)
  (display "Stages: ") (display (length STAGE-ORDER)) (newline)
  (for-each (lambda (s) (display "  - ") (display (stage-name s)) (newline)) STAGE-ORDER)
  (let ((ps (list-deployed-products)))
    (display "Products deployed: ") (display (length ps)) (newline)
    (for-each (lambda (p) (display "  - ") (display p) (newline)) ps)))

(define (show-products)
  (let ((s (deploy-summary)))
    (display "=== Deployed Products ===\n")
    (display "Version: ") (display (assoc-ref s 'version)) (newline)
    (display "Count: ") (display (assoc-ref s 'product-count)) (newline)))

(define (show-deploy-summary) (write-json (deploy-summary)))

(define (show-help)
  (display "AIAOS Product Closed-Loop v1.0\n")
  (display "Usage: chicken-csi -s product-closed-loop.scm [command]\n\n")
  (display "Commands:\n")
  (display "  run <id> [title]    Execute full 6-stage pipeline\n")
  (display "  status              Show closed-loop status\n")
  (display "  products            List deployed products\n")
  (display "  deploy-summary      JSON deployment summary\n")
  (display "  help                This help\n"))

(let ((args (command-line-arguments)))
  (if (null? args) (show-help)
    (let ((cmd (string->symbol (car args))))
      (case cmd
        ((run)
          (if (>= (length args) 2)
            (let ((pid (cadr args))
                  (obj (if (>= (length args) 3)
                         `((title . ,(caddr args)))
                         `((title . ,pid)))))
              (run-closed-loop pid obj))
            (show-help)))
        ((status) (show-status))
        ((products) (show-products))
        ((deploy-summary) (show-deploy-summary))
        ((help) (show-help))
        (else (show-help))))))
